# Generated by Django 4.2.5 on 2023-11-21 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='date_except',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
